-keep class org.eclipse.tm4e.core.internal.theme.raw.** { *; }
-keep class org.eclipse.tm4e.core.internal.grammar.raw.** { *; }
-keep class io.github.rosemoe.sora.langs.textmate.registry.reader.** { *; }
-keep class org.eclipse.tm4e.core.internal.parser.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes InnerClasses
-keepattributes EnclosingMethod
-keep class com.termux.terminal.JNI { *; }
-keep class com.termux.terminal.** { *; }
-keep class com.termux.view.** { *; }
